git: github
topology:
#  type:
settings:
#  cosmos_name:
#  cosmos_project:
#  bucket_name:
#  bucket_region:
foundations:
  default_visibility: public
#  default_owner:
  default_tpl_owner: x-i-a
  default_tpl_name: xia-template-foundation
structure:
#  realms:
#    realm-1:
#      realms:
#        realm-1-1:
#          realms:
#            realm-1-1-1:
#              foundations:
#                foundation-1-1-1-a:
#          foundations:
#            foundation-1-1-a:
#      foundations:
#        foundation-1-a:
#    realm-2:
#      foundations:
#        foundation-2-a:
#        foundation-2-b:
